
application.yml:
spring:
  application:
    name: smartbank-management-system

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/smart_bank
    username: root
    password: YOUR_DB_PASSWORD 
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true      
    properties:
      hibernate:
       format_sql: true  
      dialect: org.hibernate.dialect.MySQLDialect


  mail:
   host: smtp.gmail.com
   port: 587
   username: YOUR_EMAIL
   password: YOUR_MAIL_PASSWORD
   properties:
    mail:
     smtp:
       auth: true
       starttls:
         enable: true

server:
  port: 8080

logging:
   level:
     root: INFO
     com.bank.smartbank: DEBUG  # Your package logs at DEBUG level
     org.springframework.security: DEBUG  # Security logs
     org.hibernate.SQL: DEBUG  # SQL queries
   pattern:
     console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
   file:
      name: logs/smart-bank.log